---
name: Security by Submodules

on:
  pull_request:
    branches:
      - "feat/**"

concurrency:
  group: security-checks-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  secret-scanning:
    uses: dlpco/infra-github-workflows/.github/workflows/gitleaks-scan.yml@main
    secrets: inherit

  security-fs:
    uses: dlpco/infra-github-workflows/.github/workflows/trivy-fs-scan.yml@main
    secrets: inherit

  security-iac:
    uses: dlpco/infra-github-workflows/.github/workflows/trivy-iac-scan.yml@main
    secrets: inherit

  container-image-scan:
    uses: dlpco/infra-github-workflows/.github/workflows/trivy-container-scan.yml@main
    with:
      dockerfile_path: go-src/build/Dockerfile
    secrets: inherit